### ISSUE TITLE
Fix cookie test

### ISSUE THREAD

**Issue by danny-people-plus** [StafflinePeoplePlus/peopleplus-components#1178]
<img width="971" alt="image" src="https://github.com/StafflinePeoplePlus/peopleplus-components/assets/70882278/9a34e088-2936-4415-95cd-b92806a6ff71">

**Comment by jamesbirtles** [comment]
probably shouldn't have been merged 😅

**Comment by danny-people-plus** [comment]
> probably shouldn't have been merged 😅

Very true and I hang my head in shame ;>
