### ISSUE TITLE
Fix footer breakpoint 

### ISSUE THREAD

**Issue by annafatani** [StafflinePeoplePlus/peopleplus-components#1292]
![image](https://github.com/StafflinePeoplePlus/peopleplus-components/assets/79071385/d49eeb52-e5b5-47b4-a85b-445a008651b2)

Start breakpoint at lg: instead of md:

**Comment by jamesbirtles** [comment]
is this resolved by #1293 @annafatani ?

**Comment by annafatani** [comment]
Resolved by #1293
