### ISSUE TITLE
Carousel CSS doesn't load properly in dev

### ISSUE THREAD

**Issue by jamesbirtles** [StafflinePeoplePlus/peopleplus-components#159]
The css imports don't seem to work in dev when using it outside of this repo. It looks like the css loads during SSR but the hydration seems to wipe it out.

Not 100% sure what to do here, some options:
-  copy + paste the CSS into the style block
-  import it and use postcss to inline it - but then there will be warnings about unused styles..
-  Just document that you need to import the css when using the component
- Create a tailwind plugin to and just get it to spit out the css - seems weird but we might want a tailwind plugin later on anyway?
- replace swiper with something else, custom or otherwise

**Comment by danny-people-plus** [comment]
I'm up for replacing swiper if you can find an alternative.
