### ISSUE TITLE
Add sign in and sign up button to navbar

### ISSUE THREAD

**Issue by annafatani** [StafflinePeoplePlus/peopleplus-components#260]
1. Add a Sign In button feature so a user can sign in to access some restricted pages. Make this optional as this is only applicable for internal apps. 

2. Add a signup button. This will be applicable to eCommerce pages.

**Comment by jamesbirtles** [comment]
The NavBar already supports the ability to do add anything you want to it, e.g.

```svelte
<NavBar>
	<!-- other navbar slots omitted -->
	<div slot="end">
		<button
			type="button"
			on:click={() => ($page.data.session ? signOut() : signIn('auth0'))}
		>
			Sign {$page.data.session ? 'out' : 'in'}
		</button>
	</div>
</NavBar>
```

I'm not sure theres much value in specifically adding sign in / sign up buttons. We certainly are in need of a generic button however.

**Comment by jamesbirtles** [comment]
Closing as we now have a button component and the navbar supports this use case
